# Generated by Django 5.1 on 2024-08-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Social Media Platform',
                'verbose_name_plural': 'Social Media Platforms',
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust')], default='joy', max_length=10)),
                ('sound_name', models.CharField(max_length=255)),
                ('sound_url', models.URLField(blank=True, max_length=255, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_sounds', to='trending.socialmediaplatform')),
            ],
        ),
    ]
