# Generated by Django 4.2.9 on 2024-09-06 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0003_modelversion_chart_chart_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='stream_change',
        ),
        migrations.RemoveField(
            model_name='track',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='current_streams',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='streams_last_24h',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='streams_last_30d',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='streams_last_7d',
        ),
        migrations.AddField(
            model_name='trackfeatures',
            name='popularity_last_12h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackfeatures',
            name='popularity_last_24h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackfeatures',
            name='popularity_last_3d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackfeatures',
            name='popularity_last_3h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackfeatures',
            name='popularity_last_5d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackfeatures',
            name='popularity_last_6h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackfeatures',
            name='retrieval_frequency',
            field=models.CharField(blank=True, choices=[('high', 'High Frequency'), ('low', 'Low Frequency')], default='low', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='version_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='trackfeatures',
            name='current_popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackfeatures',
            name='trend',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackfeatures',
            name='velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StreamHistory',
        ),
        migrations.AddField(
            model_name='popularityhistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_history', to='trending.track'),
        ),
    ]
