# Generated by Django 4.2.9 on 2024-09-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0004_popularityhistory_remove_track_stream_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfeatures',
            name='retrieval_frequency',
            field=models.CharField(blank=True, choices=[('high', 'High Frequency'), ('medium', 'Medium Frequency'), ('low', 'Low Frequency')], default='low', max_length=50, null=True),
        ),
    ]
