# Generated by Django 4.2.9 on 2024-09-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0005_alter_trackfeatures_retrieval_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', to='trending.track'),
        ),
        migrations.DeleteModel(
            name='PlaylistTrack',
        ),
    ]
