# Generated by Django 4.2.9 on 2024-09-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0007_remove_trackfeatures_popularity_last_12h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='added_to_playlists_count',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
    ]
