# Generated by Django 4.2.9 on 2024-09-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0009_trackfeatures_mean_popularity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularityhistory',
            options={'ordering': ['-timestamp']},
        ),
    ]
