# Generated by Django 4.2.9 on 2024-09-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0010_alter_popularityhistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackfeatures',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='speechiness',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='trackfeatures',
            name='valence',
        ),
    ]
