# Generated by Django 4.2.9 on 2024-09-15 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0011_remove_trackfeatures_danceability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=50)),
                ('actual_trend', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=50, null=True)),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualized_at', models.DateTimeField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_predictions', to='trending.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(blank=True, max_length=25, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('model_type', models.CharField(choices=[('RandomForest', 'RandomForest'), ('GradientBoost', 'GradientBoost'), ('HistGradientBoost', 'HistGradientBoost')], max_length=25)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('evaluation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelPerformance',
        ),
        migrations.DeleteModel(
            name='ModelVersion',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='trend_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='trending.trendmodel'),
        ),
    ]
