# Generated by Django 4.2.9 on 2024-09-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0012_predictionhistory_trendmodel_delete_modelperformance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfeatures',
            name='predicted_trend',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trendmodel',
            name='model_type',
            field=models.CharField(choices=[('RandomForest', 'RandomForest'), ('HistGradientBoost', 'HistGradientBoost')], max_length=25),
        ),
    ]
