# Generated by Django 4.2.9 on 2024-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0014_alter_trackfeatures_predicted_trend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
