# Generated by Django 4.2.9 on 2024-09-27 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0015_track_spotify_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
        migrations.CreateModel(
            name='CustomPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_playlists', to='trending.chart')),
                ('tracks', models.ManyToManyField(blank=True, null=True, related_name='custom_playlists', to='trending.track')),
            ],
        ),
    ]
