# Generated by Django 4.2.9 on 2024-10-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0019_trackfeatures_hgb_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50)),
                ('importance', models.FloatField()),
                ('trend_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_importances', to='trending.trendmodel')),
            ],
        ),
    ]
