# Generated by Django 4.2.9 on 2024-10-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0020_featureimportance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendmodel',
            name='best_paramters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='featureimportance',
            unique_together={('trend_model', 'feature_name')},
        ),
    ]
