# Generated by Django 4.2.9 on 2024-10-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0022_alter_featureimportance_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendmodel',
            old_name='best_paramters',
            new_name='best_parameters',
        ),
        migrations.AddField(
            model_name='trendmodel',
            name='csv_data',
            field=models.FileField(blank=True, null=True, upload_to='trend_model_data_csv/'),
        ),
    ]
