# Generated by Django 4.2.9 on 2024-10-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0023_rename_best_paramters_trendmodel_best_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendmodel',
            name='confusion_matrix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trendmodel',
            name='best_parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
