# Generated by Django 4.2.9 on 2024-10-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0025_trendmodel_model_file_trendmodel_readme_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendmodel',
            name='model_type',
            field=models.CharField(choices=[('RandomForest', 'RandomForest'), ('HistGradientBoost', 'HistGradientBoost'), ('LogisticRegression', 'LogisticRegression'), ('SVM', 'SVM'), ('KernelRidge', 'KernelRidge'), ('ExtraTrees', 'ExtraTrees'), ('KNN', 'KNN')], max_length=25),
        ),
        migrations.AlterField(
            model_name='trendmodel',
            name='readme_file',
            field=models.FileField(blank=True, null=True, upload_to='trending/trend_model/readme/'),
        ),
    ]
