# Generated by Django 4.2.9 on 2024-10-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0026_alter_trendmodel_model_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendmodel',
            name='model_type',
            field=models.CharField(choices=[('RandomForest', 'RandomForest'), ('HistGradientBoost', 'HistGradientBoost'), ('LogisticRegression', 'LogisticRegression'), ('SVM', 'SVM'), ('LDA', 'LDA'), ('ExtraTrees', 'ExtraTrees'), ('KNN', 'KNN')], max_length=25),
        ),
    ]
