# Generated by Django 4.2.9 on 2024-10-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0027_alter_trendmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendmodel',
            name='popularity_timeframe',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
