# Generated by Django 4.2.9 on 2024-10-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0029_trackfeatures_extra_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendmodel',
            name='model_type',
            field=models.CharField(choices=[('RandomForest', 'RandomForest'), ('HistGradientBoosting', 'HistGradientBoosting'), ('LogisticRegression', 'LogisticRegression'), ('SVM', 'SVM'), ('LDA', 'LDA'), ('ExtraTrees', 'ExtraTrees'), ('KNN', 'KNN')], max_length=25),
        ),
    ]
