# Generated by Django 4.2.9 on 2024-10-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0030_alter_trendmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendmodel',
            name='phase_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
