# Generated by Django 4.2.9 on 2024-10-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0031_trendmodel_phase_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendmodel',
            name='model_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
