# Generated by Django 4.2.9 on 2024-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0032_trendmodel_model_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendmodel',
            name='phase_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
