# Generated by Django 4.2.9 on 2024-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0033_alter_trendmodel_phase_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('starter_script', models.FileField(blank=True, null=True, upload_to='trending/trend_model/starter_script/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
